---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Repository:
    Description: The repository this stack is deployed from.
    Type: String

  Domain:
    Description: The domain registered.
    Type: String

  HostedZoneId:
    Description: The ID of the domain registered via AWS Route53.
    Type: String

  RedirectUrl:
    Description: The URL to redirect requests to.
    Type: String

  RedirectProtocol:
    Description: The protocol to use when redirecting requests.
    Type: String
    AllowedValues: [ http, https ]
    Default: https

Conditions:
  CreateResources: !Equals [ !Ref "AWS::Region" , "ap-southeast-2" ]

Resources:
  Website:
    Type: AWS::S3::Bucket
    Condition: CreateResources
    Properties:
      BucketName: !Ref Domain
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RedirectUrl
          Protocol: !Ref RedirectProtocol
      Tags:
        - Key: repository
          Value: !Ref Repository

  WebsiteRecordSet:
    Type: AWS::Route53::RecordSet
    Condition: CreateResources
    Properties:
      Name: !Ref Website
      HostedZoneId: !Ref HostedZoneId
      Type: CNAME
      TTL: 900
      ResourceRecords:
        - !Sub "https://${Website}.s3-website-${AWS::Region}.amazonaws.com"
