---
name: CI/CD

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  # dispatch:
  #   needs: [lint]
  #   if: contains(github.event.head_commit.message, "[dispatch]")
  #   uses: ./.github/workflows/dispatch.yml
  #   with:
  #     aws-region: ap-southeast-2
  #   secrets:
  #     github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws-secret-access-key: ${{ secrets.AWS_SECRET }}

  post-to-slack:
    # needs: [dispatch]
    needs: [lint, test]
    if: always()
    uses: ./.github/workflows/post-to-slack.yml
    secrets: inherit

