---
name: CI/CD
on:
  push:
    paths:
      - '.github/workflows/.cicd.yml'
      - '.github/workflows/10-lint.yml'
      - '.github/workflows/20-test.yml'
      - '.github/workflows/80-dispatch.yml'
      - '.github/workflows/99-post-to-slack.yml'
      - 'bin/*'
      - 'cf/**'
      - 'cmd/**'
      - 'templates/**'
      - '**Dockerfile'
      - 'Makefile*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-cicd]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  lint:
    uses: ./.github/workflows/10-lint.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  test:
    uses: ./.github/workflows/20-test.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # dispatch:
  #   needs: [lint, test]
  #   if: contains(github.event.head_commit.message, '[dispatch]')
  #   uses: ./.github/workflows/80-dispatch.yml
  #   secrets: inherit

  post-to-slack:
    needs: [lint, test]
    # needs: [dispatch]
    if: always()
    uses: ./.github/workflows/99-post-to-slack.yml
    secrets:
      WEBHOOK: ${{ secrets.SLACK_GITHUB_NOTIFICATIONS_WEBHOOK }}

