---
name: CI/CD
on:
  push:
    paths:
      - '.github/workflows/.cicd.yml'
      - 'bin/*'
      - 'cf/**'
      - 'cmd/**'
      - 'templates/**'
      - '**Dockerfile'
      - 'Makefile*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-cicd]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  lint:
    uses: ./.github/workflows/10-lint.yml
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_runner_role_name: ${{ secrets.AWS_RUNNER_ROLE_NAME }}

  test:
    uses: ./.github/workflows/20-test.yml
    secrets: inherit
    with:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws-runner-role-name: ${{ secrets.AWS_RUNNER_ROLE_NAME }}

  dispatch:
    needs: [lint, test]
    if: contains(github.event.head_commit.message, "[dispatch]")
    uses: ./.github/workflows/80-dispatch.yml
    secrets: inherit
    with:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws-runner-role-name: ${{ secrets.AWS_RUNNER_ROLE_NAME }}

  post-to-slack:
    needs: [dispatch]
    if: always()
    uses: ./.github/workflows/99-post-to-slack.yml
    secrets: inherit

