---
name: Dependabot | Auto-merge
on:
  pull_request:
    types: [opened, synchronize]
  repository_dispatch:
    types: [update-dependabot-automerge]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  dependabot-automerge:
    if: startsWith(github.head_ref, 'dependabot/')
    uses: ./.github/workflows/00-dependabot-automerge.yml
