---
name: README.md
on:
  push:
    paths:
      - '.github/workflows/*' # NOTE: this must include .github/workflows/.README.yml
      - 'bin/README.sh'
      - 'templates/*'
      - 'docs/*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-readme]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  generate-readme:
    uses: ./.github/workflows/00-README.yml
    secrets: inherit

  post-to-slack:
    needs: [generate-readme]
    if: always()
    uses: ./.github/workflows/99-post-to-slack.yml
    secrets: inherit
