---
name: README.md
on:
  push:
    paths:
    - bin/README.sh
    - '.github/workflows/*'
    - 'templates/*'
    - 'docs/*'
  workflow_dispatch:

jobs:
  generate-readme:
    uses: ./.github/workflows/README.yml

  post-to-slack:
    needs: [generate-readme]
    if: always()
    uses: ./.github/workflows/post-to-slack.yml
