---
on:
  workflow_call:
    inputs:
      aws_account_id:
        description: The ID of the AWS account used to pull the docker image from.
        type: string
        required: true
      aws_region:
        description: The AWS region to pull the docker image from.
        type: string
        required: true
      aws_runner_role_name:
        description: The name of the IAM role used to assume in the AWS account.
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Setup private Go dependencies.
        run: git config --global url."https://${{ secrets.ADMIN_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::104132128521:role/github-actions
          role-session-name: github-actions
          aws-region: ap-southeast-2

      - name: Login to AWS ECR.
        uses: aws-actions/amazon-ecr-login@v2

      - name: Lint.
        run: |
          img="${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/go"
          echo "##[group]Pulling image."
          docker pull "$img"
          echo "##[endgroup]"
          docker run \
            -v "$PWD:/go/src/app" \
            -w "/go/src/app" \
            -e CI \
            "$img" \
            sh -c "make lint"
