---
on:
  workflow_call:
    inputs:
      templates:
        description: A space separated list of templates to deploy.
        type: string
        default: deploy
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_RUNNER_ROLE_NAME:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_RUNNER_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR.
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy.
        run: |
          img="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/docker/go"
          echo "##[group]Pulling image."
          docker pull "$img"
          echo "##[endgroup]"
          docker run \
            -v "$PWD:/go/src/app" \
            -w "/go/src/app" \
            -e CI \
            -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
            "$img" \
            sh -c "make ${{ inputs.templates }}"

