---
on:
  workflow_call:
    inputs:
      artifact:
        description: |
          A space separated list of the paths to artifacts to-be uploaded to AWS S3.

          The repository name will be used for the path to the bucket in AWS S3.
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_RUNNER_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: dist

      - name: Upload website.
        run: |
          make upload-dist
          depot/bin/40-sync.sh ./dist
