---
on:
  workflow_call:
    inputs:
      artifact:
        description: |
          A space separated list of the paths to artifacts that you want uploaded to AWS S3.

          The repository name will be used for the path to the bucket in AWS S3.
        type: string
        required: true
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_RUNNER_ROLE_NAME:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_RUNNER_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: dist

      - name: Upload website.
        run: |
          ls -la
          ls -la dist/
          ls -la dist/public/
          make upload
