---
on:
  workflow_call:
    secrets:
      WEBHOOK:
        required: true

jobs:
  determine-conclusion:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.determine.outputs.conclusion }}
    steps:
      - id: determine
        uses: jmpa-io/determine-workflow-conclusion@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  post:
    needs: [determine-conclusion]
    runs-on: ubuntu-latest
    steps:
      - uses: jmpa-io/post-to-slack@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          status: ${{ needs.determine-conclusion.outputs.conclusion }}
