---
name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/cicd.yml@main
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
