on:
  workflow_call:
    secrets:
      github-token:
        required: true
jobs:
  run:
    name: Run default CI/CD.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depo
          token: ${{ secrets.github-token }}