---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  post-to-slack:
    needs: [lint]
    uses: ./.github/workflows/notify.yml
    if: always()
    with:
      job-status: ${{ job.status }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
