on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    name: Determining which CI/CD to run.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depo
          token: ${{ secrets.github-token }}

      - name: Listing repository topics.
        id: list-topics
        run: echo "topics=$(bin/list-repo-topics.sh $GITHUB_REPOSITORY)"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - run: echo "$topics"  

