---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

jobs:
  # lint:
  #   uses: ./.github/workflows/lint.yml
  #   secrets:
  #     github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  test2:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1

  determine-conclusion:
    needs: [test2]
    if: always()
    runs-on: ubuntu-20.04
    outputs:
      conclusion: ${{ steps.determine.outputs.conclusion }}
    steps:
      - id: determine
        run: |
          out=success
          [[ ${{ needs.test2.result }} == "failure" ]] \
            && out=failure
          echo "::set-output name=conclusion::$out"

  post-to-slack:
    needs: [determine-conclusion]
    uses: ./.github/workflows/notify.yml
    if: always()
    with:
      workflow-conclusion: ${{ needs.determine-conclusion.outputs.conclusion }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
