on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    name: Determining which CI/CD to run.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depo
          token: ${{ secrets.github-token }}

      - name: Retrieve repository topics.
        run: |
          topics=$(bin/list-repo-topics.sh $GITHUB_REPOSITORY)
          [[ -z "$topics" ]] && { exit 1; }
          echo "TOPICS=$topics" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - run: echo "$topics"
        if: contains(env.TOPICS, 'template')  

