---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  test2:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1

  determine-workflow-conclusion:
    needs: [lint, test2]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'
          success=false
          if [[ "${{ needs.lint.result }}" == "success" && "${{ needs.test2.result}}" == "success" ]]; then
            success=true
          fi
          echo "WORKFLOW_CONCLUSION=$success" >> $GITHUB_ENV

  post-to-slack:
    needs: [determine-workflow-conclusion]
    uses: ./.github/workflows/notify.yml
    if: always()
    with:
      workflow-conclusion: ${{ env.WORKFLOW_CONCLUSION }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
