on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    name: Run CI/CD.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depo
          token: ${{ secrets.github-token }}

      - name: Retrieve repository topics.
        run: |
          topics=$(bin/list-repo-topics.sh $GITHUB_REPOSITORY)
          [[ -z "$topics" ]] && { topics="empty"; }
          echo "TOPICS=$topics" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - if: contains(env.TOPICS, 'template')
        run: echo "${{ env.TOPICS }}"

      - if: contains(env.TOPICS, 'actions')
        run: echo "${{ env.TOPICS }}"

      - if: contains(env.TOPICS, 'empty')
        uses: ./.github/workflows/cicd-default.yml
