---
name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: Run CI/CD.
    uses: ./.github/workflows/cicd.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
