on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  determine-what-to-run:
    name: Determining which CI/CD to run.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depo
          token: ${{ secrets.github-token }}

      - name: Listing repository tags.
        run: bin/list-repo-topics.sh $GITHUB_REPOSITORY

  # TODO add the generic jobs here.
