---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

jobs:
  # lint:
  #   uses: ./.github/workflows/lint.yml
  #   secrets:
  #     github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  test2:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1

  post-to-slack:
    needs: [test2]
    if: always()
    uses: ./.github/workflows/notify.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
