---
on:
  workflow_call:
    secrets:
      github-token:
        required: true
      slack-webhook:
        required: true

jobs:
  run:
    name: Run CI/CD.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout.
        uses: actions/checkout@v2

      - name: Checkout depot.
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Setup depot.
        run: |
          [[ -d bin ]] || { mkdir -p bin; }
          [[ -d .github/templates ]] || { mkdir -p .github/templates; }
          mv depot/bin/* bin
          mv depot/.github/templates/* .github/templates

      - name: Retrieve repository topics.
        run: |
          topics=$(bin/00-repo-topics.sh $GITHUB_REPOSITORY)
          [[ -z "$topics" ]] && { topics="default"; }
          echo "topics found: $topics"
          echo "TOPICS=$topics" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: CI/CD | template.
        if: contains(env.TOPICS, 'template')
        run: |
          bin/10-lint.sh

      - name: CI/CD | actions.
        if: contains(env.TOPICS, 'actions')
        run: |
          bin/10-lint.sh

      - name: CI/CD | default.
        if: contains(env.TOPICS, 'default')
        run: |
          bin/10-lint.sh

      - name: Notify Slack.
        if: always()
        uses: jmpa-oss/notify-slack@v0.0.1
        with:
          webhook: ${{ secrets.slack-webhook }}
          status: ${{ job.status }}
