---
on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: jmpa-io/determine-workflow-conclusion@v0.0.1
        with:
          token: ${{ secrets.github-token }}
