---
on:
  workflow_call:
    inputs:
      template:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout depot.
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Setup depot.
        run: |
          [[ -d bin ]] || { mkdir -p bin; }
          [[ -d .github/templates ]] || { mkdir -p .github/templates; }
          mv -n depot/bin/* bin
          mv -n depot/.github/templates/* .github/templates

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ap-southeast-2

      - name: Deploy.
        run: bin/30-deploy.sh ${{ inputs.template }}
