---
on:
  workflow_call:
    inputs:
      templates:
        description: A space separated list of templates to deploy.
        required: true
        type: string
      artifact:
        description: The name of the artifact uploaded in the workflow.
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: Checkout roots.
        if: ${{ github.repository }} != "roots"
        uses: actions/checkout@v3
        with:
          repository: jmpa-io/roots
          ref: rework
          token: ${{ secrets.GITHUB_TOKEN }}
          path: roots

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_RUNNER_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download artifact.
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ inputs.artifact }}
          path: dist

      - name: Login to AWS ECR.
        uses: aws-actions/amazon-ecr-login@v1.6.2

      - name: Lint.
        run: |
          echo ${{ inputs.templates }}
          echo ${{ inputs.artifact }}

          docker run \
            -v "$PWD:/go/src/app" \
            -w "/go/src/app" \
            -e CI \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/go \
            sh -c "echo "


      # - name: Deploy.
      #   run: depot/bin/30-deploy.sh ${{ inputs.templates }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github-token }}
