---
on:
  workflow_call:
    secrets:
      github-token:
        required: true
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout depot.
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Setup depot.
        run: |
          [[ -d bin ]] || { mkdir -p bin; }
          [[ -d .github/templates ]] || { mkdir -p .github/templates; }
          mv -n depot/bin/* bin
          mv -n depot/.github/templates/* .github/templates

      - name: Lint.
        run: bin/10-lint.sh
