---
on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: Checkout depot.
        uses: actions/checkout@v3
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Lint.
        run: bin/10-lint.sh
