---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  # dispatch:
  #   needs: [lint]
  #   if: contains(github.event.head_commit.message, "[dispatch]")
  #   uses: ./.github/workflows/dispatch.yml
  #   with:
  #     aws-region: ap-southeast-2
  #   secrets:
  #     github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws-secret-access-key: ${{ secrets.AWS_SECRET }}

  post-to-slack:
    needs: [dispatch]
    if: always()
    uses: ./.github/workflows/post-to-slack.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
