---
name: README.md
on:
  push:
    paths:
    - bin/README.sh
    - '.github/workflows/*'
    - 'templates/*'
    - 'docs/*'
  workflow_dispatch:

jobs:
  generate-readme:
    uses: ./.github/workflows/README.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}

  post-to-slack:
    needs: [generate-readme]
    if: always()
    uses: ./.github/workflows/post-to-slack.yml
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
