---
on:
  workflow_call:

jobs:
  determine-conclusion:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.determine.outputs.conclusion }}
    steps:
      - id: determine
        uses: jmpa-io/determine-workflow-conclusion@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  post:
    needs: [determine-conclusion]
    runs-on: ubuntu-latest
    steps:
      - uses: jmpa-io/post-to-slack@v0.0.1
        with:
          webhook: ${{ secrets.SLACK_GITHUB_NOTIFICATIONS_WEBHOOK }}
          status: ${{ needs.determine-conclusion.outputs.conclusion }}
