on:
  workflow_dispatch:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    name: Updating README.md with new changes.
    runs-on: ubuntu-20.04
    if: github.repository != "jmpa-io/depo"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depo
          token: ${{ secrets.github-token }}
  
      - name: test
        run: ls -la

      - name: hello world?
        run: pwd