name: Updates README.md
on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  call-workflow:
    uses: jmpa-io/depo/.github/workflows/README.yml@main
    with:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}