name: Update README.md?
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: jmpa-io/depo/.github/workflows/README.yml@main
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
