on:
  workflow_call:
    # secrets:
    #   github-token:
    #     required: true

jobs:
  run:
    name: Updating README.md with new changes.
    runs-on: ubuntu-20.04
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     token: ${{ secrets.github-token }}
  
      - name: test
        run: ls
