---
on:
  workflow_call:
    secrets:
      github-token:
        required: true
      slack-webhook:
        required: true

jobs:
  run:
    name: Updating README.md, if there are any changes.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout.
        uses: actions/checkout@v2

      - name: Checkout depot.
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Setup depot.
        run: |
          [[ -d bin ]] || { mkdir -p bin; }
          [[ -d .github/templates ]] || { mkdir -p .github/templates; }
          [[ -d cf ]] || { mkdir -p cf; }
          mv depot/bin/* bin
          mv depot/.github/templates/* .github/templates/*
          mv depot/cf/* cf

      - name: Run.
        run: bin/00-README.sh jmpa-io
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Commit?
        run: bin/00-commit.sh

      - name: Notify Slack.
        if: always()
        uses: jmpa-oss/notify-slack@v0.0.1
        with:
          webhook: ${{ secrets.slack-webhook }}
          status: ${{ job.status }}
