---
on:
  workflow_call:
    secrets:
      github-token:
        required: true
      slack-webhook:
        required: true

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: Checkout depot.
        uses: actions/checkout@v3
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Generate README.md.
        run: depot/bin/README.md.sh jmpa-io
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Commit?
        run: depot/bin/commit.sh
