---
on:
  workflow_call:
    secrets:
      github-token:
        required: true
      slack-webhook:
        required: true

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout.
        uses: actions/checkout@v2

      - name: Checkout depot.
        uses: actions/checkout@v2
        with:
          repository: jmpa-io/depot
          ref: main
          token: ${{ secrets.github-token }}
          path: depot

      - name: Setup depot.
        run: |
          [[ -d bin ]] || { mkdir -p bin; }
          [[ -d .github/templates ]] || { mkdir -p .github/templates; }
          mv -n depot/bin/* bin
          mv -n depot/.github/templates/* .github/templates

      - name: Generate README.md.
        run: bin/00-README.sh jmpa-io
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Commit?
        run: bin/00-commit.sh
