name: Call a reusable workflow
on:
  push:
    branches: [main, master]

jobs:
  call-workflow:
    uses: jmpa-io/bin/.github/workflows/README.md.yml@main
    secrets:
      token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      